#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -x

wmake libso libraries

wmake applications/solvers/rhoDST


# ----------------------------------------------------------------- end-of-file
