#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory

runApplication blockMesh
runApplication decomposePar
runParallel rhoDST 4

runApplication reconstructPar 

rm -rf processor*

#------------------------------------------------------------------------------
